apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-santa-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-santa-app
  template:
    metadata:
      labels:
        app: nestjs-santa-app
    spec:
      containers:
        - name: nestjs-santa-app
          image: nestjs-santa-app
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_PORT
              value: '3000'
            - name: MAIL_HOST
              value: 'smtp.ethereal.email'
            - name: MAIL_PORT
              value: '587'
            - name: MAIL_USER
              value: 'dock.feil57@ethereal.email'
            - name: MAIL_PASS
              value: '15tdpGVqF5hxPumqE4'
            - name: MAIL_FROM
              value: 'do_not_reply@northpole.com'
            - name: MAIL_TO
              value: 'dock.feil57@ethereal.email'
            - name: USERS_LIST_LINK
              value: 'https://raw.githubusercontent.com/alj-devops/santa-data/master/users.json'
            - name: USERS_PROFILE_LINK
              value: 'https://raw.githubusercontent.com/alj-devops/santa-data/master/userProfiles.json'
